/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BarbersRouteImport } from './routes/barbers'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as StylesRouteImport } from './routes/styles'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BarbersRoute = BarbersRouteImport.update({
  id: '/barbers',
  path: '/barbers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const StylesRoute = StylesRouteImport.update({
  id: '/styles',
  path: '/styles',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/barbers': typeof BarbersRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/styles': typeof StylesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/barbers': typeof BarbersRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/styles': typeof StylesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/barbers': typeof BarbersRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/styles': typeof StylesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/barbers' | '/contact' | '/services' | '/styles'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/barbers' | '/contact' | '/services' | '/styles'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/barbers'
    | '/contact'
    | '/services'
    | '/styles'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BarbersRoute: typeof BarbersRoute
  ContactRoute: typeof ContactRoute
  ServicesRoute: typeof ServicesRoute
  StylesRoute: typeof StylesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/barbers': {
      id: '/barbers'
      path: '/barbers'
      fullPath: '/barbers'
      preLoaderRoute: typeof BarbersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/styles': {
      id: '/styles'
      path: '/styles'
      fullPath: '/styles'
      preLoaderRoute: typeof StylesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BarbersRoute: BarbersRoute,
  ContactRoute: ContactRoute,
  ServicesRoute: ServicesRoute,
  StylesRoute: StylesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
